name: Code activity (1 year)

on:
  schedule:
    - cron: "15 1 * * *" # chaque jour 01:15 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install gnuplot
        run: sudo apt-get update && sudo apt-get install -y gnuplot

      - name: Build daily added/removed (last 365 days)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p stats

          # Date range: last 365 days (UTC)
          start=$(date -u -d "365 days ago" +%Y-%m-%d)
          end=$(date -u +%Y-%m-%d)

          echo "date added removed net" > stats/code_activity_1y.dat

          d="$start"
          while [ "$d" != "$(date -u -d "$end + 1 day" +%Y-%m-%d)" ]; do
            added=$(git log --since="$d 00:00:00" --until="$d 23:59:59" --pretty=tformat: --numstat \
              | awk '{a+=$1} END {print a+0}')
            removed=$(git log --since="$d 00:00:00" --until="$d 23:59:59" --pretty=tformat: --numstat \
              | awk '{r+=$2} END {print r+0}')
            net=$((added-removed))
            echo "$d $added $removed $net" >> stats/code_activity_1y.dat
            d=$(date -u -d "$d + 1 day" +%Y-%m-%d)
          done

      - name: Generate SVG chart
        shell: bash
        run: |
          gnuplot <<'EOF'
          set terminal svg size 1100,420
          set output 'stats/code_activity_1y.svg'
          set title "Lignes de code par jour (12 derniers mois)"
          set xdata time
          set timefmt "%Y-%m-%d"
          set format x "%m/%y"
          set xlabel "Date"
          set ylabel "Lignes"
          set grid
          set key top left
          set datafile separator whitespace

          # colonnes: date added removed net
          plot 'stats/code_activity_1y.dat' using 1:2 with lines title 'Ajoutées', \
               'stats/code_activity_1y.dat' using 1:3 with lines title 'Supprimées', \
               'stats/code_activity_1y.dat' using 1:4 with lines title 'Net (ajoutées - supprimées)'
          EOF

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "igor@mages.pro"
          git add stats/code_activity_1y.dat stats/code_activity_1y.svg
          git commit -m "chore: update code activity (1y)" || echo "No changes"
          git push
